/*

-- Selections to create Tables:
⬇️

-- [1] TRY

SELECT DISTINCT
	n.planet_name,
	o.planet_type,
	n.host_star_name,
	n.spectral_type,
	o.distance,
	n.discovery_year,
	n.discovery_method,
	n.orbital_period_days,
	o.mass_multiplier,
	o.mass_wrt,
	n.planet_mass_earth_mass,
	n.planet_mass_jupiter_mass,
	o.radius_multiplier,
	o.radius_wrt,
	n.planet_radius_earth_radius,
	n.planet_radius_jupiter_radius
FROM new_data AS n
INNER JOIN old_data AS o ON n.planet_name = o.name;



-- [2] TRY

SELECT COUNT(DISTINCT (host_star_name))
FROM new_data;


-- [3] TRY

SELECT DISTINCT
 	c.planet_id,
	n.planet_name,
	o.planet_type,
	n.host_star_name,
	s.star_id,
	c.spectral_type,
	c.mass_multiplier,
	c.mass_wrt,
	c.orbital_period_days,
	c.radius_wrt,
	c.radius_multiplier,
	c.distance,
	c.discovery_year
FROM complete_data AS c
JOIN new_data AS n ON n.host_star_name = c.host_star_name
JOIN stars AS s ON s.host_star_name = n.host_star_name
JOIN old_data AS o ON o.name = n.planet_name;


-- [4] TRY

SELECT DISTINCT
	c.planet_id,
	c.planet_name,
	c.planet_type,
	c.host_star_name,
	s.star_id,
	c.spectral_type,
	c.mass_multiplier,
	c.mass_wrt,
	c.orbital_period_days,
	c.radius_wrt,
	c.radius_multiplier,
	c.distance,
	c.discovery_year
FROM complete_data AS c
JOIN stars AS s USING (host_star_name)
GROUP BY c.planet_id,
         c.planet_name,
         c.planet_type,
         c.host_star_name,
         s.star_id,
         c.spectral_type,
         c.mass_multiplier,
         c.mass_wrt,
         c.orbital_period_days,
         c.radius_wrt,
         c.radius_multiplier,
         c.distance,
         c.discovery_year;


-- [5] TRY

SELECT
	planet_id,
	planet_name,
	planet_type,
	star_id
FROM finalshape_fulldata
WHERE planet_type = 'Terrestrial'
GROUP BY planet_id
ORDER BY planet_id;


-- because im lazy, just a few queries i dont want to write
-- over & over again while refactoring ...😎🤣✌️
⬇️

ALTER TABLE finalshape_fulldata
ADD COLUMN planet_id INT PRIMARY KEY
		GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE stars
ADD COLUMN star_id INT PRIMARY KEY
		GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE cleaned_full_data
DROP COLUMN index;

ALTER TABLE cleaned_full_data
DROP COLUMN planet_id;

ALTER TABLE cleaned_full_data
DROP COLUMN star_id;

ALTER TABLE stars
DROP COLUMN planet_id;

ALTER TABLE finalshape_fulldata
DROP COLUMN index;

ALTER TABLE finalshape_fulldata
DROP COLUMN planet_id;

ALTER TABLE values
DROP COLUMN index;

ALTER TABLE finalshape_fulldata
ADD FOREIGN KEY (star_id)
REFERENCES stars (star_id);

ALTER TABLE finalshape_fulldata
ADD FOREIGN KEY (star_id)
REFERENCES stars (star_id);

ALTER TABLE stars
ADD COLUMN planet_id INT
REFERENCES finalshape_fulldata (planet_id);

ALTER TABLE values
ADD FOREIGN KEY (planet_id)
REFERENCES finalshape_fulldata (planet_id);

ALTER TABLE values
ADD FOREIGN KEY (star_id)
REFERENCES stars (star_id);


ALTER TABLE planets
DROP COLUMN index;

ALTER TABLE terrestrial_planets
DROP COLUMN index;

ALTER TABLE super_earth_planets
DROP COLUMN index;

ALTER TABLE gas_giant_planets
DROP COLUMN index;

ALTER TABLE neptune_like_planets
DROP COLUMN index;

ALTER TABLE unknown_planets
DROP COLUMN index;



ALTER TABLE planets
ADD FOREIGN KEY (planet_id)
REFERENCES fullsize_nasa_dataset (planet_id);

ALTER TABLE planets
ADD FOREIGN KEY (star_id)
REFERENCES stars (star_id);

ALTER TABLE terrestrial_planets
ADD FOREIGN KEY (planet_id)
REFERENCES fullsize_nasa_dataset (planet_id);

ALTER TABLE terrestrial_planets
ADD FOREIGN KEY (star_id)
REFERENCES stars (star_id);

ALTER TABLE super_earth_planets
ADD FOREIGN KEY (planet_id)
REFERENCES fullsize_nasa_dataset (planet_id);

ALTER TABLE super_earth_planets
ADD FOREIGN KEY (star_id)
REFERENCES stars (star_id);

ALTER TABLE gas_giant_planets
ADD FOREIGN KEY (planet_id)
REFERENCES fullsize_nasa_dataset (planet_id);

ALTER TABLE gas_giant_planets
ADD FOREIGN KEY (star_id)
REFERENCES stars (star_id);

ALTER TABLE neptune_like_planets
ADD FOREIGN KEY (planet_id)
REFERENCES fullsize_nasa_dataset (planet_id);

ALTER TABLE neptune_like_planets
ADD FOREIGN KEY (star_id)
REFERENCES stars (star_id);


ALTER TABLE unknown_planets
ADD FOREIGN KEY (planet_id)
REFERENCES fullsize_nasa_dataset (planet_id);

ALTER TABLE unknown_planets
ADD FOREIGN KEY (star_id)
REFERENCES stars (star_id);

*/
